In [8]:
import numpy as np
import time

In [11]:
#execution time
size = 100_000

#for python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]  #every single value is iterated to get the square
end = time.time()
print(f"Python List Time: {end-start} seconds")

#for numpy arrays
np_arr = np.array(py_list)
start = time.time()
sq_arr = np_arr**2  #we will get the square of every single value in nthe numpy array
end = time.time()
print(f"NumPy List Time: {end-start} seconds")


Python List Time: 0.012107372283935547 seconds
NumPy List Time: 0.0006883144378662109 seconds


In [14]:
## creating numpy array from the list
arr = np.array([1,2,3,4,5])
print(arr,type(arr),arr.shape)

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2,type(arr2),arr2.shape)

arr2D = np.array([[1,2,3],[4,5,6],[6,7,8]])
print(arr2D,type(arr2D),arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,)
[[1 2 3]
 [4 5 6]
 [6 7 8]] <class 'numpy.ndarray'> (3, 3)


In [28]:
##Properties 
print('-------2D Array------')
arr2D = np.array([[1,2,3],[4,5,6],[6,7,8]])
print(arr2D.shape)
print(arr2D.size)
print(arr2D.dtype)
print(arr2D.ndim)

print('-------2D Array to float------')
float_arr = arr2D.astype(np.float64)
print(float_arr,float_arr.dtype)

print('-------3D Array------')
arr3D = np.array([[[1,2,3],[4,5,6],[6,7,8]],[[1,2,3],[4,5,6],[6,7,8]]])
print(arr3D.shape)
print(arr3D.size)
print(arr3D.dtype)
print(arr3D.ndim)

-------2D Array------
(3, 3)
9
int64
2
-------2D Array to float------
[[1. 2. 3.]
 [4. 5. 6.]
 [6. 7. 8.]] float64
-------3D Array------
(2, 3, 3)
18
int64
3
